spring:
  application:
    name: KnowledgeHub

  datasource:
    url: jdbc:h2:mem:knowledgehub
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080

jwt:
  secret: "KnowledgeHubSecretKeyKnowledgeHubSecretKey123456789"
  expiration: 86400000